### ISSUE TITLE
never pairs

### ISSUE THREAD

**Issue by paulsayed** [aelveborn/Wii-Scale#1]
I install all but left in this message:
Listening on localhost:8080

**Comment by aelveborn** [comment]
Then the webserver should be running. Browse to http://localhost:8080 from that machine and you should see the interface. Then press the red button under the battery hatch to sync your Wii-Balanceboard.

**Comment by paulsayed** [comment]
I do all that, but still fails to pair.
I'm working on Raspberry Pi, is why it does not work?
![captura](https://cloud.githubusercontent.com/assets/12116973/7591234/3da22c96-f892-11e4-83eb-5f727481fda0.PNG)

**Comment by aelveborn** [comment]
Hi again, the problem could be that your usb bluetooth dongle is not supported by the Wii Balance Board, see compatibility here http://wiibrew.org/wiki/List_of_Working_Bluetooth_Devices or the drivers for your usb blutooth dongle is not compatible with your raspberry pi.

**Comment by aelveborn** [comment]
So it seems that raspbian has a faulty version on python pygame by default. The unit tests for pygame would not run successfully. I have removed the dependency of pygame so the last version of Wii-Scale should be able to run on raspberry pi now.

**Comment by aelveborn** [comment]
Closing issue.
