### ISSUE TITLE
Pi can pair but Wii Scale cannot connect

### ISSUE THREAD

**Issue by maffbm** [aelveborn/Wii-Scale#21]
Hi, I just got a Pi for this project (cheaper than buying smart scales!) so I'm relatively new to all thing Linux so apologies.
I have followed the instructions, got it all installed, go it to start up on a restart, running "bind-setup" sees the balance board, the Pi itself in Raspbian can also pair to the board, however in the browser clicking connect does see the  board, any ideas?

Also, I ran this: npm config set wii-scale:host 0.0.0.0
as well as giving my Pi a static IP and set the port to 8082 (8080 and 8081 are in use on my home network) but I cannot see it outside of the Pi on my Windows or Android devices, am I supposed to be able to?

One more thing, I ran this command: npm config set wii-scale:address 00:00:00:00:00
however I must have got the address wrong as I had 12 characters, not 10 so I tried by removing the first 2 and again with removing the last 2, is there a way to reset this back to default?

And as others have mentioned, pounds would be great rather than kilos (or both?)

Many thanks.

**Comment by ribbons** [comment]
The current python-based back-end only connects if you press the red 'sync' button under the battery cover each time you try to connect.  However, for some people's setups (mine included) it won't even connect then.  I believe that the board has to _not_ be paired for it to work.

I've re-written the back-end in C++ in PR #17, so you should get better results with that code if you give it a try.  The C++ back-end doesn't need the MAC address of the balance board to be set and also needs the balance board to be paired (like you have it currently).  Let me know if the new back-end works for you - the more data points the better!

**Comment by maffbm** [comment]
thanks @ribbons , how would I install that version please? github/linux is still a steep learning curve for me

**Comment by ribbons** [comment]
You can install it by getting the code from https://github.com/ribbons/Wii-Scale/tree/cpp-back-end and following the build & install instructions there.
