### ISSUE TITLE
npm start doesn't work on pi

### ISSUE THREAD

**Issue by maojh** [aelveborn/Wii-Scale#22]
Hi, I'm trying to install wii-scale on a raspberryPi 3 and during installation I get this error after "npm start".
Probably it's a problem on my system and not with the wii-scale code, clues?

[npm start Err.txt](https://github.com/aelveborn/Wii-Scale/files/1078290/npm.start.Err.txt)
[npm-debug.log.txt](https://github.com/aelveborn/Wii-Scale/files/1078289/npm-debug.log.txt)

**Comment by graycube** [comment]
@maojh Had the same problem, try `sudo apt-get install nodejs-legacy`. It worked for me.

**Comment by aelveborn** [comment]
Has been open long enough without comments, closing issue. Pro tip: #26 explains some findings using RPi3.
