### ISSUE TITLE
Front end graph stop drawing after a few months of stored data.

### ISSUE THREAD

**Issue by Nauttor** [aelveborn/Wii-Scale#23]
I´m an intensive user of the system, my wife to be more concrete, and after a few months the graph stop drawing. It happened to me before and the only workaround it's to create a new user and start again but you lose all data.

@aelveborn can you check on the issue please?

Just for the record I attach below a screen capture of the issue.

<img width="1074" alt="screen shot 2017-06-21 at 19 14 40" src="https://user-images.githubusercontent.com/17730164/27397410-7dea2b6c-56b6-11e7-9444-b4d6a0283361.png">

**Comment by sahoahfoa** [comment]
Can you post your app-data.json file and any relevant nodejs logs? It'll help a lot in debugging this.

**Comment by Nauttor** [comment]
Sure, I'll upload it later today.

**Comment by sahoahfoa** [comment]
I think I have it figured out. I believe the graph is only showing the first 14 data points instead of the last 14. The for loop that builds the data set for the graph is fine but assumed the data points would be appended to the end of the list instead of the beginning. I'll submit a PR tomorrow evening to fix it.

**Comment by Nauttor** [comment]
Wow, that was fast sahoahfoa, thanks. 

I'll test your patch in order to confirm your thoughts. 

Regards.

**Comment by sahoahfoa** [comment]
Kinda new to git... I buggered up that last PR. Try this branch https://github.com/sahoahfoa/Wii-Scale/tree/fix-graph

**Comment by ribbons** [comment]
As @sahoahfoa's PR is closed but not merged, I've added a similar fix for this issue to my fork at https://github.com/ribbons/Wii-Scale so it doesn't get forgotten

**Comment by aelveborn** [comment]
Should have been merged to master now. Closing issue.

**Comment by ribbons** [comment]
> Should have been merged to master now. Closing issue.

Sorry @aelveborn - I wasn't as clear as I should have been - the fix was merged to the master branch at my fork rather than the cpp backend branch, so this fix didn't get merged.  I've raised PR #29 for it.

**Comment by aelveborn** [comment]
@ribbons oh I see, I merged your PR.
