### ISSUE TITLE
Increase the reading precision

### ISSUE THREAD

**Issue by rabbit52068** [aelveborn/Wii-Scale#45]
First, I just want to say thank you to the dev, really like the project.
Just want to know how to modify the weight number from 1 decimal place to 2 or even 3 decimal places.
Thanks in advance for any help.

**Comment by ribbons** [comment]
The number of decimal places is currently [hard-coded](https://github.com/aelveborn/Wii-Scale/blob/266c292e3d60d822f8a9d7ab4624387e891a06e3/web/public/source/scripts/controllers.js#L134) but it could be made configurable.  I've got a half-finished patch on my fork which adds the ability to display the weights in pounds or pounds and stones which I really must finish off and submit a PR for.

**Comment by rabbit52068** [comment]
Thanks @ribbons ,this helps a lot!
I'll close this issue.
